========================================================================
Try catch type inference
========================================================================
fun main(arg: int | null) {
    try {
        assert (arg != null) throw 10;
//!                                ^ int
        arg;
//!     ^ int
    } catch {
        arg;
//!     ^ int?
    }
}
------------------------------------------------------------------------
ok

========================================================================
Try catch first variable type inference
========================================================================
fun main(arg: int | null) {
    try {
        assert (arg != null) throw 10;
    } catch (e) {
        e;
//!     ^ int
    }
}
------------------------------------------------------------------------
ok

========================================================================
Try catch second variable type inference
========================================================================
fun main(arg: int | null) {
    try {
        assert (arg != null) throw 10;
    } catch (e, d) {
        d;
//!     ^ unknown
    }
}
------------------------------------------------------------------------
ok
